#!/bin/sh
#
# batch -- create multiple containers in one script
#
# usage:
#
# E.x.:
#    users="a b c d e f g" peruser=3 labs="linux-0.11-lab cs630-qemu-lab" \
#          host="myhost" cleanup=1 security=0 tools/deploy/batch
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null 2>&1

[ -z "$users" ] && users="ubuntu"
[ -z "$peruser" ] && peruser=1
[ -z "$labs" ] && labs=linux-0.11-lab
[ -z "$cleanup" ] && cleanup=0
[ -z "$security" ] && security=2

if [ -z "$host" ]; then
    do_unlock
    get_var HOST localhost
    host=$HOST
    do_lock
fi


LAB_SECURITY=$security

. ${TOP_DIR}/tools/deploy/init

for lab in $labs
do
  ${TOP_DIR}/tools/docker/choose $lab

  if [ $cleanup -eq 1 ]; then
    ${TOP_DIR}/tools/deploy/rm $lab
    ${TOP_DIR}/tools/deploy/clean $lab
    ${TOP_DIR}/tools/docker/choose $lab
  fi

  ${TOP_DIR}/tools/docker/unlock $lab

  echo $host > ${TOP_DIR}/.host_name

  for user in $users
  do
    ${TOP_DIR}/tools/deploy/run $lab $user $peruser
  done

  ${TOP_DIR}/tools/deploy/release all
done
