#!/bin/sh

read -p 'This command is dangerous, are you sure? (yes/no) ' sure

[ "x$sure" != 'xyes' ] && exit 0

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

filter=$1
[ -n "$2" ] && filter=$2

deploy_do_clean $filter
