#!/bin/sh
#
# clean-all
#
# Copyright (C) 2016-2020 Wu Zhangjin <lzufalcon@163.com>
#

export RELEASE=0

uname | grep -q MINGW && PWD_OPT="-W"
TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd $PWD_OPT)"
. "$TOP_DIR/tools/docker/config" $* >/dev/null

filter=all

. "${TOP_DIR}/tools/deploy/clean"

rm -rf "$RELEASE_FILE"
