#!/bin/sh

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

. ${TOP_DIR}/tools/deploy/clean

do_unlock

$SUDO rm -rf $LAB_OUTPUT/${CURRENT}*

$SUDO git clean -fdx >/dev/null 2>&1
