#!/bin/sh

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

[ -z "$LAB_NAME" -o "$1" = "all" ] && LAB_NAME=".*"

if [ -z "$filter" ]; then
  filter=$1
  [ -n "$2" ] && filter=$2
fi

get_lab_info $TOP_DIR/tools/deploy/list "$filter"
