#!/bin/sh

export RELEASE=0

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

. ${TOP_DIR}/tools/deploy/rm

docker ps -a --format='{{.ID}}' | xargs -I{} docker rm -f {} 2>&1

rm -rf $RELEASE_FILE
