#!/bin/sh

read -p 'This command is dangerous, are you sure? (yes/no) ' sure

[ "x$sure" != 'xyes' ] && exit 0

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

[ ! -d $LAB_OUTPUT ] && exit 0

start_cmds=`find $LAB_OUTPUT/${CURRENT}*/ -name "start" | grep -v deploy`

for start_cmd in $start_cmds
do
    lab_name=$(echo $start_cmd | sed -e 's%$LAB_OUTPUT%%g' | cut -d'+' -f1)
    lab_name=$(basename $lab_name)

    $start_cmd $lab_name
done
