#!/bin/sh

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

if [ -z "$filter" ]; then
  filter=$1
  [ -n "$2" ] && filter=$2
fi

deploy_do start 'Starting' $filter
