#!/bin/sh

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

[ ! -d $LAB_OUTPUT ] && exit 0

stop_cmds=`find $LAB_OUTPUT/${CURRENT}*/ -name "stop" | grep -v deploy`

for stop_cmd in $stop_cmds
do
    lab_name=$(echo $stop_cmd | sed -e 's%$LAB_OUTPUT%%g' | cut -d'+' -f1)
    lab_name=$(basename $lab_name)

    $stop_cmd $lab_name
done
