#!/bin/bash

container_ip=$(ifconfig eth0 | grep "inet " | tr -d -c '^[0-9. ]' | awk '{print $1}')
[ -z "$container_ip" ] && container_ip=$(ifconfig br0 | grep "inet " | tr -d -c '^[0-9. ]' | awk '{print $1}')

DESKTOP=/home/$UNIX_USER/Desktop/
local_shortcut_count=`find $DESKTOP -name local.desktop | wc -l`
[ $local_shortcut_count -ne 0 ] \
    && find $DESKTOP -name local.desktop | xargs -i sudo -u $UNIX_USER sed -i -e "s%localhost%$container_ip%g" {}
