#!/bin/sh
#
# autodeploy -- deploy some labs automatically
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

[ "x$HOST_OS" != "xLinux" ] && echo "LOG: Only available for Linux currently." && exit 1

DST=/usr/local/bin/cloud-lab-autodeploy
SRC=$TOP_DIR/tools/deploy/batch
CRON=/etc/cron.hourly/0cloud-lab
LOG=/var/log/cloud-lab.autodeploy.log

[ -z "$loop" ] && loop=2
[ -z "$interval" ] && interval="30s"
[ -z "$alive" ] && alive="30m"
[ -z "$cleanup" ] && cleanup=1
[ -z "$peruser" ] && peruser=2
[ -z "$labs" ] && labs="linux-0.11-lab cs630-qemu-lab markdown-lab tinylab.org linux-lab"
[ -z "$prompt" ] && prompt="<p><em>说明</em>：以下帐号仅供免费体验，半小时更新一组，感谢 青云QingCloud 赞助服务器。</p>"

[ `id -u` -ne 0 ] && SUDO=sudo

echo "LOG: create cron tasks"

$SUDO touch $LOG
$SUDO chown $HOST_USER:$HOST_USER $LOG

$SUDO /bin/bash -c "echo -e \"#!/bin/bash\n\nmyself=\\$\\$\nps -ef | grep cloud-lab | tr -s ' ' | cut -d' ' -f2 | tr -d $\"myself\" | xargs -I{} sudo kill -9 {}\n\nsudo -u $HOST_USER peruser=$peruser loop=$loop interval=$interval alive=$alive cleanup=$cleanup labs='$labs' prompt='$prompt' $SRC | tee $LOG\" > $DST"
$SUDO /bin/bash -c "echo -e \"#!/bin/bash\n$DST\" > $CRON"

$SUDO chmod a+x $DST $CRON
$SUDO chmod o-r $LOG
$SUDO service cron restart
