#!/bin/sh
#
# autodeploy -- deploy some labs automatically
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

[ "x$HOST_OS" != "xLinux" ] && echo "LOG: Only available for Linux currently." && exit 1

DST=/usr/local/bin/cloud-lab-autodeploy
SRC=$TOP_DIR/tools/deploy/batch
CRON=/etc/cron.hourly/0cloud-lab
LOG=/var/log/cloud-lab.autodeploy.log

[ -z "$loop" ] && loop=2
[ -z "$interval" ] && interval="30s"
[ -z "$alive" ] && alive="30m"
[ -z "$cleanup" ] && cleanup=1
[ -z "$peruser" ] && peruser=3
[ -z "$labs" ] && labs=`echo $LABS | tr '\n' ' '`
[ -z "$prompt" ] && prompt="<p><em>说明</em>：以下帐号仅供免费体验，半小时更新一组，每个帐号限一人使用，感谢 青云QingCloud 赞助服务器。</p>"

[ `id -u` -ne 0 ] && SUDO=sudo

echo "LOG: create cron tasks"

$SUDO touch $LOG
$SUDO chown $HOST_USER:$HOST_USER $LOG

$SUDO /bin/bash -c "echo -e \"#!/bin/bash\nsudo -u $HOST_USER prompt='$prompt' peruser=$peruser loop=$loop interval=$interval alive=$alive cleanup=$cleanup labs='$labs' $SRC | tee $LOG\" > $DST"
$SUDO /bin/bash -c "echo -e \"#!/bin/bash\n$DST\" > $CRON"

$SUDO chmod a+x $DST $CRON
$SUDO chmod o-r $LOG
$SUDO service cron restart
