#!/bin/sh
#
# bash -- Start shell in a container with root for debugging
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
. "$TOP_DIR"/tools/docker/config >/dev/null

lab_id=$(docker ps -f name=$CONTAINER_NAME -f status=running -q)
[ -z "$lab_id" ] && echo "LOG: $LAB_NAME is not running." && exit 1

[ -z "$UNIX_USER" ] && get_var UNIX_USER $DEF_USER

do_op "$WINPTY docker exec -it -w $LAB_WORKDIR/$CURRENT -u $UNIX_USER" CONTAINER_NAME "//bin/bash"
