#!/bin/bash
#
# bash -- Start shell in a container with root for debugging
#

TOP_DIR=$(cd $(dirname $0) && pwd)/../../
source $TOP_DIR/tools/docker/config $* >/dev/null

do_op "docker exec -t -i " CONTAINER_ID "/bin/bash"
