#!/bin/sh
#
# build -- Build the docker image for the lab
#
# ref: https://docs.docker.com/engine/installation/linux/ubuntulinux/
#
# E.g. LAB_CACHE=0 tools/docer/build
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

[ -n "$LAB_CACHE" -a "x$LAB_CACHE" = "x0"  ] && NO_CACHE="--no-cache"

do_op "docker build $NO_CACHE -t " IMAGE $CONFIG_DIR
