#!/bin/sh
#
# build-all
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

# markdown-lab must be built before qing-lab

for lab in $LABS
do
    echo "\n\n========== Building tinylab/$lab ==========\n\n"

    $DOCKER_BUILD_CMD $lab

    [ $? -ne 0 ] && exit 1
done
