#!/bin/sh
#
# clean-all -- clean all docker labs
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

export RELEASE=0

read -p 'This command is dangerous, are you sure? (Yes/No) ' sure

[ "x$sure" != 'xyes' -a "x$sure" != 'xY' -a "x$sure" != 'xy' -a "x$sure" != 'xYES' ] && exit 0

TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
. "$TOP_DIR"/tools/docker/config >/dev/null

for lab in `get_labs`
do
  current=$lab
  unset CONTAINER_NAME
  . "$TOP_DIR"/tools/docker/config>/dev/null 2>&1

  # Ignore the containers not exists
  [ -z "$CONTAINER_NAME" ] && continue

  "$DOCKER_CLEAN_CMD" $lab

done

"$DOCKER_RM_ALL_CMD"

# clean up the ip:token mappings for webvnc
[ -z "$LOCAL_TOKEN_MAP" -o "$REMOTE_TOKEN_MAP" ] && prepare_export_files
if [ -f "$LOCAL_TOKEN_MAP" -a -f "$REMOTE_TOKEN_MAP" -a "$LOCAL_TOKEN_DIR" != "/" ]; then
  rm -rf "$LOCAL_TOKEN_DIR"
fi

rm -rf "$LAB_LOGIN"
rm -rf "$LAB_VNC"
rm -rf "$LAB_HOST"

"$DOCKER_RELEASE_CMD" all >/dev/null 2>&1
