#!/bin/sh
#
# clean -- clean a docker lab
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

uname | grep -q MINGW && PWD_OPT="-W"
TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd $PWD_OPT)"
. "$TOP_DIR/tools/docker/config" $* >/dev/null

notify_user 2 "Lab will be removed"

do_unlock

# Remove container
[ -n "$CONTAINER_NAME" ] && do_op "docker rm -f" CONTAINER_NAME

# Remove desktop shortcut
# do_op "rm -f" LOCAL_DESKTOP_SHORTCUT

# Remove the token map from .vnc-tokens/local_map
[ -n "$VNC_TOKEN" ] && do_op "sed -i -e \"/$VNC_TOKEN/d\"" LOCAL_TOKEN_MAP

find "$CONFIG_DOCKER_DIR" -iname ".[^.]*" -exec rm -rf "{}" \;

# Update lab list
[ "$RELEASE" != '0' ] && "$DOCKER_RELEASE_CMD" all >/dev/null 2>&1
