#!/bin/sh
#
# clean -- clean a docker lab
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

do_unlock

# Notify users
[ -z "$NOTIFY_WAIT" ] && NOTIFY_WAIT=2
[ -z "$NOTIFY_MSG" ] && NOTIFY_MSG="Container will be removed in $NOTIFY_WAIT seconds"
$DOCKER_NOTIFY_CMD $LAB_NAME "$NOTIFY_MSG" && sleep $NOTIFY_WAIT

# Remove container
do_op "docker rm -f" CONTAINER_NAME

# Remove desktop shortcut
do_op "rm -f" LOCAL_DESKTOP_SHORTCUT

find $CONFIG_DOCKER_DIR -iname ".[^.]*" -exec rm -rf {} \;
