#!/bin/sh
#
# clean-all -- clean all docker labs
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

export RELEASE=0

read -p 'WARN: This command is dangerous, are you sure? (Yes/No) ' sure

[ "x$sure" != 'xyes' -a "x$sure" != 'xY' -a "x$sure" != 'xy' -a "x$sure" != 'xYES' ] && exit 0

TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
. "$TOP_DIR"/tools/docker/config >/dev/null

log_print "Get all of the labs"
labs=`get_labs`
log_end

for lab in $labs
do
  current=$lab
  unset CONTAINER_NAME
  log_print "Check status of $lab"
  . "$TOP_DIR"/tools/docker/config >/dev/null 2>&1

  # Ignore the containers not exists
  [ -z "$CONTAINER_NAME" ] && continue

  log_print "Clean $lab"
  "$DOCKER_CLEAN_CMD" $lab
  log_end

done

log_print "Remove containers"
RELEASE=0 "$DOCKER_RM_ALL_CMD"
log_end

log_print "clean up for webvnc"
[ -z "$LOCAL_TOKEN_MAP" -o "$REMOTE_TOKEN_MAP" ] && prepare_export_files
if [ -f "$LOCAL_TOKEN_MAP" -a -f "$REMOTE_TOKEN_MAP" -a "$LOCAL_TOKEN_DIR" != "/" ]; then
  do_op "rm -rf" LOCAL_TOKEN_DIR
fi
log_end

log_print "Remove general cached data"
for f in LAB_LOGIN LAB_VNC LAB_HOST LAB_CURRENT
do
  do_op "rm -rf" $f
done
log_end

log_print "Remove lab manager and browser shotcuts"
remove_shortcuts
log_end

[ -z "$labs" ] && info_print "No lab is found." && exit 0

log_print "Update release page"
"$DOCKER_RELEASE_CMD" all >/dev/null 2>&1
log_end
