#!/bin/bash
#
# clean-service -- clean the docker service
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
. "$TOP_DIR"/tools/docker/config >/dev/null

# Fix up the port already used issue
info_print "Stopping docker-proxy"
sudo pkill docker-proxy

info_print "Restarting docker service"
# Restart docker service
sudo systemctl restart docker
