#!/bin/sh
#
# commit -- commit/save a running lab container to image
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
. "$TOP_DIR"/tools/docker/config $* >/dev/null

if [ -z "$TAG" ]; then
  TAG=local-$(date +"%Y%m%d%H%M%S")
fi

IMAGE=$LAB_USER/$CURRENT:$TAG

do_op "docker commit" CONTAINER_NAME "$IMAGE"

do_unlock
set_var IMAGE
do_lock

echo "LOG: new image name saved to $IMAGE"
