#!/bin/sh
#
# git-pull-all -- pull all labs' repositories
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
. "$TOP_DIR"/tools/docker/config >/dev/null

for lab in `get_labs`
do
    echo "LOG: Pulling repository: $lab"

    lab_dir="$LAB_DIR"/$lab
    [ -d "$lab_dir" ] && cd "$lab_dir" && git pull -v
done
