#!/bin/sh
#
# git-pull -- pull the latest lab
#

uname | grep -q MINGW && PWD_OPT="-W"
TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd $PWD_OPT)"
. "$TOP_DIR"/tools/docker/config $* >/dev/null

echo "LOG: pulling repository: $LAB_NAME"

cd "$LAB_DIR/$LAB_NAME" && git pull -v
