#!/bin/sh
#
# install -- Install docker engine
#
# Usage: tools/docker/install [registry-mirror-site]
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#
# ref: https://docs.docker.com/engine/installation/linux/ubuntulinux/
#
# ref: https://jpetazzo.github.io/2014/01/29/docker-device-mapper-resize/
#
# ref: https://mirror.tuna.tsinghua.edu.cn/help/docker-ce/
#

which docker > /dev/null 2>&1 && exit 0

# Allow customize docker registry mirror sites, use 'no' argument to using default servers
[ -n "$1" ] && REGISTRY_MIRROR=$1
[ -z "$REGISTRY_MIRROR" ] && REGISTRY_MIRROR=https://docker.mirrors.ustc.edu.cn

[ -n "$2" ] && DOCKER_MIRROR=$2
[ -z "$DOCKER_MIRROR" ] && DOCKER_MIRROR=mirrors.163.com

[ -f /etc/issue ] && grep -qi ubuntu /etc/issue
if [ $? -eq 0 ]; then
    echo "INFO: Install docker-ce with $0"
else
    echo
    echo "WARN: Docker is missing, but it is required by Linux Lab, please prepare one:"
    echo
    echo "1. Get a preinstalled Linux Lab Disk from https://shop155917374.taobao.com/"
    echo
    echo "   It is able to compile and boot a new linux kernel in 5 minutes."
    echo
    echo "2. For Linux, Install docker manually"
    echo
    echo "   $ curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh"
    echo
    echo "3. For Windows, please install Docker Toolbox without wsl or Docker Desktop with wsl2"
    echo
    echo "   Docker Toolbox: https://get.daocloud.io/toolbox/"
    echo "   Docker Desktop: https://docs.docker.com/desktop/windows/install/"
    echo
    echo "4. For MacOS, please refer to https://docs.docker.com/desktop/mac/install/"
    echo
    echo "Contact us via wechat: tinylab."
    echo
    echo "And free courses are available from: https://www.cctalk.com/m/group/88948325"
    echo
    exit 1
fi

# Install docker-engine for Ubuntu

HOST_USER=`whoami`
[ "x$HOST_USER" = "xroot" -a -n "$SUDO_USER" ] && HOST_USER=$SUDO_USER
[ `id -u` -ne 0 ] && SUDO=sudo

$SUDO apt-get -y update
$SUDO apt-get install -y curl software-properties-common
$SUDO curl -fsSL http://$DOCKER_MIRROR/docker-ce/linux/ubuntu/gpg | sudo apt-key add -
ubuntu_version=$(lsb_release -cs)
$SUDO add-apt-repository -y "deb [arch=amd64] http://$DOCKER_MIRROR/docker-ce/linux/ubuntu $ubuntu_version stable"
$SUDO apt-get -y update
$SUDO apt-get -y install apt-transport-https ca-certificates
$SUDO apt-get -y install bridge-utils
$SUDO apt-get -y install net-tools vim git

[ "$ubuntu_version" = "trusty" ] && $SUDO apt-get -y install linux-image-extra-$(uname -r) linux-image-extra-virtual
$SUDO apt-get -y --force-yes install docker-ce
$SUDO usermod -aG docker $HOST_USER

# Add registry-mirror for newer docker
if [ ! -f /etc/docker/daemon.json -a -n "$REGISTRY_MIRROR" ]; then
$SUDO bash -c 'cat <<EOF > /etc/docker/daemon.json
{
  "registry-mirrors": ["'$REGISTRY_MIRROR'"]
}
EOF'
fi

# Restart to make sure the above opts work
$SUDO ifconfig docker0 down
$SUDO brctl delbr docker0
$SUDO service docker restart

# FIXME: 'newgrp' not work in script, perhaps should use 'sg' instead
# see: https://unix.stackexchange.com/questions/18796/how-to-apply-changes-of-newly-added-user-groups-without-needing-to-reboot
echo "INFO: Without reboot, please issue 'newgrp docker' to work in docker group" >&2
