#!/bin/sh
#
# lock -- Lock configs and tools
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

uname | grep -q MINGW && PWD_OPT="-W"
TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd $PWD_OPT)"
. "$TOP_DIR"/tools/docker/config $* >/dev/null

do_lock
