#!/bin/sh
#
# monitor -- monitor a docker lab
#
# Copyright (C) 2016-2020 Wu Zhangjin <lzufalcon@163.com>
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

do_op "docker stats" CONTAINER_NAME
