#!/bin/sh
#
# cmd -- Start any cmd in a container
#

uname | grep -q MINGW && PWD_OPT="-W"
TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd $PWD_OPT)"
. "$TOP_DIR/tools/docker/config" $* >/dev/null

[ -z "$1" ] && echo "Usage: $0 [lab-name] msg" && exit 0

msg=$1
[ -n "$2" ] && msg=$2

cmd="//bin/bash -c 'export DISPLAY=:1 && notify-send -u critical -t 0 "
cmd="$cmd \"$msg\""
cmd="$cmd '"

docker ps -f name=$CONTAINER_NAME | grep -qv PORTS
[ $? -ne 0 ] && echo "LOG: $LAB_NAME is not running." && exit 1

do_op "docker exec" CONTAINER_ID "$cmd"
