#!/bin/sh
#
# Prune a clean docker environment.
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

# Will this clean up the increasing files /run/udev/data/+cgroup:*

read -p 'WARN: This command is dangerous, are you sure? say no if not sure. (yes/no) ' sure

docker system prune
