#!/bin/bash
#
# pull-all -- pull the docker images from docker hub
#

TOP_DIR=$(cd $(dirname $0) && pwd)/../../
source $TOP_DIR/tools/docker/config $* >/dev/null

(docker search $LAB_USER | grep -q $LAB_NAME) || (echo "LOG: No $IMAGE found in docker hub" && exit 1)

for IMAGE in $IMAGES
do
    do_op "docker pull" IMAGE
done
