#!/bin/sh
#
# pull-all -- pull the docker images from docker hub
#

uname | grep -q MINGW && PWD_OPT="-W"
TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd $PWD_OPT)"
. "$TOP_DIR"/tools/docker/config $* >/dev/null

for IMAGE in $IMAGES
do
    do_op "docker pull" IMAGE
done
