#!/bin/sh
#
# push -- push a docker image to docker hub
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
. "$TOP_DIR"/tools/docker/config >/dev/null

for IMAGE in `get_images`
do
    do_op "docker push" IMAGE
done
