#!/bin/sh

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

[ ! -f $TOP_DIR/README.md ] && exit 0

[ -z "$LAB_NAME" -o "$1" = "all" ] && LAB_NAME=" "

get_labs $TOP_DIR/tools/docker/list
