#!/bin/sh
#
# rerun -- remove a docker lab and rerun it
#
# Copyright (C) 2016-2020 Wu Zhangjin <lzufalcon@163.com>
#

uname | grep -q MINGW && PWD_OPT="-W"
TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd $PWD_OPT)"
. "$TOP_DIR"/tools/docker/config $* >/dev/null

"$DOCKER_RM_CMD" $LAB_NAME

"$DOCKER_RUN_CMD" $LAB_NAME
