#!/bin/sh
#
# rm -- remove a docker lab
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

notify_user 2 "Container will be removed"

# Remove container
do_op "docker rm -f" CONTAINER_NAME

# Remove desktop shortcut
do_op "rm -f" LOCAL_DESKTOP_SHORTCUT
