#!/bin/sh
#
# rm-full -- remove full of docker labs
#

export RELEASE=0

uname | grep -q MINGW && PWD_OPT="-W"
TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd $PWD_OPT)"
. "$TOP_DIR"/tools/docker/config $* >/dev/null

id_names=`docker ps -f status=running -f status=exited --format='{{.ID}},{{.Names}}' | sed '1!G;h;$!d'`

for id_name in $id_names
do
    id=$(echo $id_name | cut -d ',' -f1)
    name=$(echo $id_name | cut -d ',' -f2)

    lab=`echo $name | sed -e "s%-[0-9]*$%%g"`
    echo $LABS $WPROXY_NAME $TPROXY_NAME | tr ' ' '\n' | grep -q ^$lab$
    [ $? -ne 0 ] && continue

    echo "Removing $name ..."

    force=0
    ls "${LAB_OUTPUT}/$name*/" >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        "${LAB_OUTPUT}/$name*/tools/docker/rm" $lab
    elif [ -d "${TOP_DIR}/configs/$lab" ]; then
        "$DOCKER_RM_CMD" $lab
    else
        force=1
    fi

    # Force remove at last
    [ $? -ne 0 ] && force=1
    [ $force -eq 1 ] && docker rm -f $id
done

"$DOCKER_RELEASE_CMD" all >/dev/null 2>&1
