#!/bin/sh
#
# rmi-all -- remove all of the none images
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

docker images | grep "<none>"  | tr -s ' ' | cut -d' ' -f3 | xargs -I{} docker rmi -f {}
