#!/bin/sh
#
# run-all -- run all docker labs
#

uname | grep -q MINGW && PWD_OPT="-W"
TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd $PWD_OPT)"
. "$TOP_DIR"/tools/docker/config $* >/dev/null

for lab in $LABS
do
  "$DOCKER_RUN_CMD" $lab
done
