#!/bin/sh
#
# ssh -- login the docker lab via ssh
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
. "$TOP_DIR"/tools/docker/config >/dev/null

get_vars UNIX_PWD UNIX_USER VNC_IP

which sshpass >/dev/null 2>&1
[ $? -eq 0 ] && SSH_PASS="sshpass -p '$UNIX_PWD'"

SSH_CMD="$SSH_PASS ssh -X -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -t ${UNIX_USER}@${VNC_IP} -p ${CONTAINER_SSH_PORT} 'cd $LAB_WORKDIR/$CURRENT && exec bash -l'"

if [ -z "$SSH_PASS" ]; then
  echo
  echo "LOG: Password '$UNIX_PWD' required, please login with the following command:"
  echo
  echo "  $SSH_CMD"
  echo

  echo "LOG: If want to login without password, there are two methods:"
  echo
  echo "  1. Install the 'sshpass' command"
  echo

  cat <<EOF
  2. Upload public ssh key with following steps:

        $ mkdir ~/.ssh/
        $ touch ~/.ssh/authorized_keys
        $ chmod 700 ~/.ssh/
        $ chmod 644 ~/.ssh/authorized_keys
        $ vim ~/.ssh/authorized_keys

        Generate a public ssh key with 'ssh-keygen'
        Copy your public ssh key and paste it into the ~/.ssh/authorized_key

EOF

fi

echo
echo "LOG: Enabling X11 Forwarding support"
echo

which xhost >/dev/null 2>&1
[ $? -eq 0 ] && xhost +

cat <<EOF > ~/.ssh/ssh-x11-forward.config
# X11 Forwarding Support
Host *
   ForwardAgent yes
   ForwardX11 yes
   ForwardX11Trusted yes
EOF

echo
echo "LOG: Running '$SSH_CMD'"
echo

eval "$SSH_CMD"
