#!/bin/sh
#
# start-all -- start all stopped docker lab
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

export RELEASE=0

TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
. "$TOP_DIR"/tools/docker/config >/dev/null

id_names=`docker ps -f status=exited --format='{{.ID}},{{.Names}}' | sed '1!G;h;$!d'`

for id_name in $id_names
do
    id=$(echo $id_name | cut -d ',' -f1)
    name=$(echo $id_name | cut -d ',' -f2)

    lab=`echo $name | sed -e "s%-[0-9]*-[0-9a-zA-Z]\{6,6\}$%%g"`
    echo `get_labs` $WPROXY_NAME $TPROXY_NAME | tr ' ' '\n' | grep -q ^$lab$
    [ $? -ne 0 ] && continue

    echo "Starting $name ..."

    ns="$(find \"$LAB_OUTPUT\" -type d -name \"$name*\" 2>/dev/null)"

    if [ -n "$ns" ]; then
        for n in $ns
        do
            "$LAB_OUTPUT"/$n/tools/docker/stop $lab
        done
    elif [ -d "$TOP_DIR"/configs/$lab ]; then
        "$DOCKER_START_CMD" $lab
    else
        docker start $id
    fi
done

sleep 5

"$DOCKER_RELEASE_CMD" all >/dev/null 2>&1
