#!/bin/sh
#
# start -- start a stopped docker lab
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

# Require to prepare some environment for docker containers in host
[ -f $LAB_HOST_RUN ] && $LAB_HOST_RUN

do_op "docker start" CONTAINER_ID

[ "$RELEASE" != '0' ] &&  $DOCKER_RELEASE_CMD all >/dev/null 2>&1
