#!/bin/bash
#
# start-all -- start all stopped docker lab
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)

id_names=`docker ps -a --format='{{.ID}},{{.Names}}' | tac`

for id_name in $id_names
do
    id=$(echo $id_name | cut -d ',' -f1)
    name=$(echo $id_name | cut -d ',' -f2)
    lab_name=${name%-*}

    echo "Starting $name ..."

    if [ -d ${TOP_DIR}/configs/$lab_name ]; then
        ${TOP_DIR}/tools/docker/start $lab_name
    else
        docker start $id
    fi
done
