#!/bin/sh
#
# stop -- stop a docker lab
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

notify_user 2 "Container will be stopped"

do_op "docker stop" CONTAINER_ID
