#!/bin/sh
#
# stop -- stop a docker lab
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
. $TOP_DIR/tools/docker/config $* >/dev/null

# Notify users
[ -z "$NOTIFY_WAIT" ] && NOTIFY_WAIT=2
[ -z "$NOTIFY_MSG" ] && NOTIFY_MSG="Container will be stopped in $NOTIFY_WAIT seconds"
$DOCKER_NOTIFY_CMD $LAB_NAME "$NOTIFY_MSG" && sleep $NOTIFY_WAIT

do_op "docker stop" CONTAINER_ID
