#!/bin/bash
#
# trun -- Run the docker image with in transparent proxy available environment
#
# Usage:
#
#    $ trun lab_name
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)

# Configuration

[ -z "$PROXY_SERVER" -o -z "$PROXY_PWD" ] \
	&& echo "Error: Must configure PROXY_SERVER and PROXY_PWD." && exit 1

[ -z "$ENCRYPT_CMD" ] && ENCRYPT_CMD=md5sum
[ -z "$PROXY_LIMIT" ] && PROXY_LIMIT=0

# Run

PROXY_SERVER=$PROXY_SERVER \
PROXY_PWD=$PROXY_PWD \
ENCRYPT_CMD=$ENCRYPT_CMD \
PROXY_LIMIT=$PROXY_LIMIT \
TPROXY=1 \
${TOP_DIR}/tools/docker/run $1
