#!/bin/sh
#
# unlock -- unlock configs and tools
#

LAB_SECURITY=1

uname | grep -q MINGW && PWD_OPT="-W"
TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd $PWD_OPT)"
. "$TOP_DIR"/tools/docker/config $* >/dev/null

do_unlock
