#!/bin/sh
#
# unlock -- unlock configs and tools
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

LAB_SECURITY=1

TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
. "$TOP_DIR"/tools/docker/config $* >/dev/null

do_unlock
