#!/bin/bash
#
# vnc -- open the docker lab's novnc frontend via a browser
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
source $TOP_DIR/tools/docker/config $* >/dev/null

do_unlock

get_var WEB_BROWSER chromium-browser
get_var HOST localhost
get_var VNC_PWD ubuntu
get_var CONTAINER_NAME

do_lock

which $WEB_BROWSER >/dev/null 2>&1
if [ $? -eq 1 ]; then
    echo "LOG: No $WEB_BROWSER found, use firefox instead."
    WEB_BROWSER=firefox
fi

[ -z "$VNC_AUTOCONNECT" ] && VNC_AUTOCONNECT=0
[ -z "$ENCRYPT_CMD" ] && ENCRYPT_CMD=md5sum
[ -z "$TOKEN_LENGTH" ] && TOKEN_LENGTH=6
CONTAINER_IP=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CONTAINER_NAME`
token=`echo -n $CONTAINER_IP | $ENCRYPT_CMD | cut -d' ' -f1 | cut -c1-$TOKEN_LENGTH`

# Get vnc page
HOST_WEB_URL="$WEB_HTTP://localhost:${CONTAINER_VNC_PORT}/vnc.html?token=$token&password=$VNC_PWD&autoconnect=$VNC_AUTOCONNECT&encrypt=$WEB_ENCRYPT"
REMOTE_WEB_URL="$WEB_HTTP://${HOST}:${HOST_VNC_PORT}/vnc.html?token=$token&password=$VNC_PWD&autoconnect=$VNC_AUTOCONNECT&encrypt=$WEB_ENCRYPT"

# Create local shotcut on Desktop
if [ -d ~/Desktop -a -n "$REMOTE_DESKTOP_SHORTCUT" -a -f "$REMOTE_DESKTOP_SHORTCUT" ]; then
    echo '#!/usr/bin/env xdg-open' > $LOCAL_DESKTOP_SHORTCUT
    if [ "$WEB_BROWSER" == "chromium-browser" ]; then
        icon=chromium-browser.png
    else
        icon=firefox.png
    fi

    TMP_URL=`echo $HOST_WEB_URL | tr '&' '|'`
    cat $REMOTE_DESKTOP_SHORTCUT \
        | sed "s%Exec=.*%Exec=$WEB_BROWSER $TMP_URL%g" \
        | sed "s%terminator.png%$icon%g;s%lxterminal.xpm%$icon%g" | tr '|' '&' \
	  >> $LOCAL_DESKTOP_SHORTCUT
    chmod a+x $LOCAL_DESKTOP_SHORTCUT
fi

# For web portmapping
[ -f $LAB_PORTMAP ] && grep -q ":8" $LAB_PORTMAP \
    && (docker logs $CONTAINER_ID 2>/dev/null | grep "Server address:") \
    && for port in $(grep ":8" $LAB_PORTMAP | cut -d':' -f1); \
       do echo "LOG: Local Web Address: http://$HOST:$port/"; done

which $WEB_BROWSER >/dev/null 2>&1 \
    && ($WEB_BROWSER $HOST_WEB_URL >/dev/null 2>&1 &)>/dev/null 2>&1

echo "Please login $REMOTE_WEB_URL"
