#!/bin/bash
#
# web -- access the docker lab via 80 port
#

TOP_DIR=$(cd $(dirname $0) && pwd)/../../
source $TOP_DIR/tools/docker/config $* >/dev/null

do_unlock
get_var WEB_BROWSER firefox
get_var HOST_NAME localhost
get_var UNIX_USER ubuntu
get_var LOCAL_VNC_PORT 6080
do_lock

which $WEB_BROWSER 2>&1>/dev/null
if [ $? -eq 1 ]; then
    echo "LOG: No $WEB_BROWSER found, use firefox instead."
    WEB_BROWSER=firefox
fi

LOCAL_WEB_PORT=`get_web_port $LOCAL_VNC_PORT`

WEB_CMD="$WEB_BROWSER http://${HOST_NAME}:${LOCAL_WEB_PORT}"

echo -e "LOG: Please browser with '$WEB_CMD'\n"

($WEB_CMD 2>&1>/dev/null &) 2>&1>/dev/null
