#!/bin/bash
#
# webssh -- login the docker lab via web ssh
#

TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
source $TOP_DIR/tools/docker/config $* >/dev/null

do_unlock
get_var WEB_BROWSER chromium-browser
get_var HOST localhost
get_var UNIX_USER ubuntu
get_var UNIX_PWD ubuntu
do_lock

which $WEB_BROWSER >/dev/null 2>&1
if [ $? -eq 1 ]; then
    echo "LOG: No $WEB_BROWSER found, use firefox instead."
    WEB_BROWSER=firefox
fi

CONTAINER_IP=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CONTAINER_NAME`
WEBSSH_CMD="$WEB_BROWSER $WEB_HTTP://${HOST}:${LOCAL_WEBSSH_PORT}?ssh=ssh://$UNIX_USER:$UNIX_PWD@$CONTAINER_IP:$REMOTE_SSH_PORT"

echo -e "LOG: Please login with 'ip=$CONTAINER_IP, port=$REMOTE_SSH_PORT, user=$UNIX_USER, password=$UNIX_PWD' and enter workdir: $LAB_WORKDIR\n"

($WEBSSH_CMD >/dev/null 2>&1 &) >/dev/null 2>&1
