#!/bin/bash
#
# zram-swap -- enable zram as swap
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#

size=$1
if [ -z "$size" ]; then
    total=$(grep MemTotal /proc/meminfo | tr -s ' ' | cut -d ' ' -f2)
    size=$((total / 1024 / 1024 / 3))
fi

swapon | grep -q zram
if [ $? -ne 0 ]; then
    modprobe zram
    echo $((size*1024*1024*1024)) > /sys/block/zram0/disksize
    mkswap /dev/zram0
    swapon /dev/zram0
fi
