#!/bin/bash
#
# zram-raw -- enable zram
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#
# Requirements:
#
# $ sudo apt-get install -y bcache-tools
#

size=$1
if [ -z "$size" ]; then
    total=$(grep MemTotal /proc/meminfo | tr -s ' ' | cut -d ' ' -f2)
    size=$((total / 1024 / 1024 / 3))
fi

modprobe zram
echo $((size*1024*1024*1024)) > /sys/block/zram0/disksize
