#!/bin/bash
#
# zram-bcache -- enable zram as bcache
#
# Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
#
# Requirements:
#
# $ sudo apt-get install -y bcache-tools
#

size=$1
if [ -z "$size" ]; then
    total=$(grep MemTotal /proc/meminfo | tr -s ' ' | cut -d ' ' -f2)
    size=$((total / 1024 / 1024 / 3))
fi

swapon | grep -q zram
if [ $? -ne 0 ]; then
    modprobe bcache
    modprobe zram
    echo 3 > /sys/block/zram0/max_comp_streams
    echo $((size*1024*1024*1024)) > /sys/block/zram0/disksize
    make-bcache -C /dev/zram0 --wipe-bcache
    bcache-super-show /dev/zram0
fi
